In [7]:
import numpy
n = numpy.arange(27)
type(n) # numpy.ndarray
print(n)

numpy.ndarray

In [8]:
# This reshapes n into 2 dim array
n.reshape(3, 9)
# This reshapes n into 3 dim array
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
# This changes normal array to numpy array
m = numpy.array([[10, 20, 24], [1], []])
# type([[10, 20, 24], [1], []]) # => list
# type(m) # => numpy.ndarray
m


array([list([10, 20, 24]), list([1]), list([])], dtype=object)

In [18]:
import cv2
im_g = cv2.imread("files/smallgray.png", 0) # 0 gray scale 1 bgr (rgb)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [21]:
cv2.imwrite("files/newsmallgray.png", im_g)

True

In [26]:
im_g[0:2, 2:4]
# im_g[2,4] # => 182
# im_g.shape # => (3, 5)

182

In [29]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [33]:
# Stacking arrays horizontally
ims = numpy.hstack((im_g, im_g))
# numpy.hstack((im_g, im_g)) # This would stack arrays vertically
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [38]:
# Splitting an array horizontally
lst = numpy.hsplit(ims, 2)
lst  # split into 2 arrays

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [44]:
# Splitting an array vertically
lst = numpy.vsplit(ims, 3)
lst # split into 3 arrays
#lst[0] # => array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8)

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8)